---
title: "final_proj"
output: html_document
---

# Setup
```{r setup}
library(xlsx)
library(tidyverse)
library(stringr)
library(plyr)
library(dplyr)
library(readr)
library(ggplot2)
# install.packages("devtools")
# devtools::install_github("haleyjeppson/ggmosaic")
# library(ggmosaic)

STATES <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming")
```

# Data gathering
Ex: In terminal, download data via
> wget https://www.justice.gov/crt/about/vot/notices/vnote022712.xls

Picking data URL
```{r}
dates <- seq(as.Date("2010-09-27"), as.Date("2012-07-30"), by = 1)
urls <- paste("https://www.justice.gov/crt/about/vot/notices/vnote",
              str_sub(dates, 6, 7),
              str_sub(dates, 9, 10),
              str_sub(dates, 3, 4),
              ".xls", sep = "")
```

Downloading the data
```{r, eval = FALSE}
oldw <- getOption("warn")
options(warn = -1)
for (url in urls) {
    tryCatch(download.file(url,
                           paste("./data/", str_sub(url, 47), sep = ""),
                           quiet = FALSE),
             error = function(e) print("")) #consider tracking the successful urls   
}
options(warn = oldw)
```

# Data preprocessing

Tidying the data
```{r}
read_and_tidy <- function(fileName) {
  file_messy <- read.xlsx(fileName, sheetName = "Sheet1")
  file <- file_messy %>%
    select(1, 4, 7, 11, 15, 18, 21, 25) %>%
    unite(NA..23, NA..23, NA..19) %>%
    dplyr::rename(state = NA.,
                  county = NA..3,
                  subjurisdiction = NA..5,
                  submission = NA..9,
                  action_date = NA..13,
                  action = NA..16,
                  changes = NA..23) %>%
    filter(state %in% STATES) %>%
    mutate(action_date = as.Date(action_date, "%m/%d/%Y"),
           changes = str_replace(changes, "_NA", ""),
           changes = str_replace(changes, "NA_", ""))
  
  # Replace NA values in certain county & subjurisdiction fields, which threw errors when working through Ubuntu
  levels <- levels(file$county)
  levels[length(levels) + 1] <- "None"
  file$county <- factor(file$county, levels = levels)
  file$county[is.na(file$county)] <- "None"
  levels <- levels(file$subjurisdiction)
  levels[length(levels) + 1] <- "None"
  file$subjurisdiction <- factor(file$subjurisdiction, levels = levels)
  file$subjurisdiction[is.na(file$subjurisdiction)] <- "None"
  return(file)
}
```

Aggregating the data
```{r}
myfiles <- list.files(path = "./data", pattern = "*.xls", full.names = TRUE)
data <- ldply(myfiles, read_and_tidy)
```

Plotting the data, using a sample without actual codes
```{r, eval = FALSE}
#testing with random sample of full data set
set.seed(1717)
samp <- data %>%
  .[sample(nrow(.), 20000), ] %>%
  mutate(code = 1 + as.integer(1 * as.integer(changes == "Redistricting plan") +
                               2 * as.integer(changes == "Annexation"))) %>%
  mutate(month = format(action_date, "%m"), year = format(action_date, "%Y")) %>%
  mutate(date = paste(year, month, sep="-")) %>%
  select('date', 'code')

samp <- samp %>%
  group_by(date, code) %>%
  dplyr::summarize(s = sum(code)) %>%
  mutate(n = s / code) %>% # assume codes are nonzero
  select(-s)
temp1 <- samp %>%
  group_by(date) %>%
  dplyr::summarize(xwidth = sum(n))
samp <- samp %>%
  left_join(temp1, by = "date") %>%
  print()

samp %>%
  ggplot(aes(x = factor(date), y = n)) +
  geom_col(aes(width = xwidth,
               fill = factor(code)),
           colour = "white",
           size = 1,
           position = position_fill(reverse = TRUE)) +
  # geom_label(aes(label = n),
  #            position = position_fill(vjust = 0.5)) +
  facet_grid(~ date, space = "free", scales = "free", switch = "x") +
  scale_x_discrete(name = "date") +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing = unit(0, "pt"))
```

Encoding the data
```{r}
data <- data %>%
  mutate(code = ifelse(str_detect(changes, paste(c("edistricting plan",
                                                   "onsolidation"),
                                                 collapse = '|')), 1,
                ifelse(str_detect(changes, paste(c("General election",
                                                   "Primary election",
                                                   "Runoff",
                                                   "Referendum",
                                                   "Election",
                                                   "f election",
                                                   "oint",
                                                   "election proced"),
                                                 collapse = '|')), 2,
                ifelse(str_detect(changes, paste(c("Absentee",
                                                   "oting method",
                                                   "oter assist"),
                                                 collapse = '|')), 3,
                ifelse(str_detect(changes, "olling place"), 4,
                ifelse(str_detect(changes, "recinct"), 5,
                ifelse(str_detect(changes, paste(c("Annexation",
                                                   "annexed area"),
                                                 collapse = '|')), 6,
                ifelse(str_detect(changes, "egistration"), 7,
                8 ))))))))
                # ifelse(str_detect(changes, "dministration"), 9,
                # ifelse(str_detect(changes, "Term of office"), 10,
                # ifelse(str_detect(changes, "Abolishment"), 11,
                # ifelse(str_detect(changes, "Ballot format"), 12,
                # ifelse(str_detect(changes, "Boundary changes"), 13,
                # ifelse(str_detect(changes, "Campaign financing"), 14,
                # ifelse(str_detect(changes, "Candidate qualification"), 15,
                # ifelse(str_detect(changes, "Compensation"), 16,
                # ifelse(str_detect(changes, "Concurrent terms"), 17,
                # ifelse(str_detect(changes, "Creation"), 18,
                # ifelse(str_detect(changes, "Deannexation"), 19,
                # ifelse(str_detect(changes, "Dissolution"), 20,
                # ifelse(str_detect(changes, "Districting"), 21,
                # ifelse(str_detect(changes, "Establishment"), 22,
                # ifelse(str_detect(changes, "Form"), 23,
                # ifelse(str_detect(changes, "Implementation Schedule"), 24,
                # ifelse(str_detect(changes, "Incorporation"), 25,
                # ifelse(str_detect(changes, "Initiative, Ref"), 26,
                # ifelse(str_detect(changes, "Limited"), 27,
                # ifelse(str_detect(changes, "Majority"), 28,
                # ifelse(str_detect(changes, "Nonpartison"), 29,
                # ifelse(str_detect(changes, "Number of officials"), 30,
                # ifelse(str_detect(changes, "Numbered positions"), 31,
                # ifelse(str_detect(changes, "Powers and duties"), 32,
                # ifelse(str_detect(changes, "Redistricting procedures"), 33,
                # ifelse(str_detect(changes, "Staggered terms"), 34,
                # ifelse(str_detect(changes, "Transfer of powers"), 35,
                # ifelse(str_detect(changes, "Voting qualification"), 36,
                # ifelse(str_detect(changes, "Nominating"), 37,
                # ifelse(str_detect(changes, "Political activity"), 38,
                # ifelse(str_detect(changes, "Procedures"), 39,
                # ifelse(str_detect(changes, "Bilingual"), 40,
                # ifelse(str_detect(changes, "selection"), 41,
                # ifelse(str_detect(changes, "staging"), 42,
                # ifelse(str_detect(changes, "Plurality"), 43,
                # ifelse(str_detect(changes, "Purge"), 44, 45)
                # ))))))))))))))))))))))))))))))))))))))))))))
```

Plotting the data (overall)
```{r}
data_p <- data %>%
  mutate(date = format(action_date, "%y %m")) %>%
  group_by(date, code) %>%
  dplyr::summarize(s = sum(code)) %>%
  mutate(n = s / code) %>% # assumes that code values are nonzero
  select(-s)
widths <- data_p %>%
  group_by(date) %>%
  dplyr::summarize(xwidth = sum(n))
data_p <- data_p %>%
  left_join(widths, by = "date") %>%
  mutate(month = format(as.Date(paste(date, "01", sep = " "), "%Y %m %d"), "%b '%y"))
data_p$month = factor(data_p$month,
                      levels=c("Sep '10", "Oct '10", "Nov '10", "Dec '10",
                               "Jan '11", "Feb '11", "Mar '11", "Apr '11", "May '11", "Jun '11",
                               "Jul '11", "Aug '11", "Sep '11", "Oct '11", "Nov '11", "Dec '11",
                               "Jan '12", "Feb '12", "Mar '12", "Apr '12", "May '12", "Jun '12",
                               "Jul '12"))

data_p %>%
  print()%>%
  ggplot(aes(x = factor(month), y = n)) +
  geom_col(aes(width = xwidth,
               fill = factor(code)),
           colour = "white",
           size = .5,
           position = position_fill(reverse = TRUE)) +
  # geom_label(aes(label = n),
  #           position = position_fill(vjust = 0.5)) +
  facet_grid(~ month, space = "free", scales = "free", switch = "x") +
  scale_x_discrete(name = "Month submitted") +
  scale_y_continuous(labels = scales::percent) +
  theme(strip.text.x = element_text(size = 6.5, angle = 0),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing = unit(0, "pt")) +
  scale_fill_discrete(name = "",
                      breaks = c("1", "2", "3", "4", "5", "6", "7", "8"),
                      labels = c("redistricting plan",
                                 "election procedures",
                                 "voting method",
                                 "polling place",
                                 "precinct",
                                 "annexation",
                                 "voter registration",
                                 "other"),
                      guide = guide_legend(reverse=TRUE)) +
  labs(title = "Preclearance Submissions for the Voting Rights Act of 1965, Section 5")
```

Plotting the data (by state)
```{r}
data_ps <- data %>%
  mutate(date = format(action_date, "%y %m")) %>%
  group_by(date, code, state) %>%
  dplyr::summarize(s = sum(code)) %>%
  mutate(n = s / code) %>% # assumes that code values are nonzero
  select(-s)
widths <- data_ps %>%
  group_by(date, state) %>%
  dplyr::summarize(xwidth = 1)
data_ps <- data_ps %>%
  left_join(widths, by = c("date", "state")) %>%
  mutate(month = format(as.Date(paste(date, "01", sep = " "), "%Y %m %d"), "%b '%y"))
data_ps$month = factor(data_ps$month,
                      levels=c("Sep '10", "Oct '10", "Nov '10", "Dec '10",
                               "Jan '11", "Feb '11", "Mar '11", "Apr '11", "May '11", "Jun '11",
                               "Jul '11", "Aug '11", "Sep '11", "Oct '11", "Nov '11", "Dec '11",
                               "Jan '12", "Feb '12", "Mar '12", "Apr '12", "May '12", "Jun '12",
                               "Jul '12"))

data_ps %>%
  print()%>%
  ggplot(aes(x = factor(month), y = n)) +
  geom_col(aes(width = xwidth,
               fill = factor(code)),
           colour = "white",
           size = .5,
           position = position_fill(reverse = TRUE)) +
  # geom_label(aes(label = n),
  #           position = position_fill(vjust = 0.5)) +
  facet_grid(~ month, space = "free", scales = "free", switch = "x") +
  scale_x_discrete(name = "Month submitted") +
  scale_y_continuous(labels = scales::percent) +
  theme(strip.text.x = element_text(size = 6.5, angle = 0),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing = unit(0, "pt")) +
  scale_fill_discrete(name = "",
                      breaks = c("1", "2", "3", "4", "5", "6", "7", "8"),
                      labels = c("redistricting plan",
                                 "election procedures",
                                 "voting method",
                                 "polling place",
                                 "precinct",
                                 "annexation",
                                 "voter registration",
                                 "other"),
                      guide = guide_legend(reverse=TRUE)) +
  labs(title = "Preclearance Submissions for the Voting Rights Act of 1965, Section 5") +
  facet_wrap(~state)
```

# Postprocessing the data (modeling)
```{r}
data_t <- data_p %>%
  select(-xwidth) %>%
  spread(key = code, value = n) %>%
  dplyr::rename(c1 = 3, c2 = 4, c3 = 5, c4 = 6, c5 = 7, c6 = 8, c7 = 9, c8 = 10)
data_t[is.na(data_t)] <- 0

prec_glm <- glm(formula = c1 ~ c2 + c3 + c4 + c5 + c6 + c7,
                      data = data_t)
summary(prec_glm)

prec_5lm <- glm(formula = c1 ~ c5,
                      data = data_t)
summary(prec_5lm)
plot(c1 ~ c5, data = data_t)
abline(prec_5lm)

prec_mlm <- glm(formula = c1 ~ c2 + c3 + c4 + c6 + c7,
                      data = data_t)
summary(prec_mlm)

prec_43lm <- glm(formula = c1 ~ c4 + c3,
                      data = data_t)
summary(prec_43lm)

prec_2lm <- glm(formula = c1 ~ c2,
                      data = data_t)
summary(prec_2lm)

# results indicate that the count of redistricting notices is best predicted by that of precinct change notices, which is unsurprising. Without this predictor, however, an accurate estimate for the redistricting count can be made from changes of polling place then of voting method.
# lastly, we note the weak correlation between counts of redistricting and of election procedure notices. This seems relieving.
```